apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeName: my-manual-pv
  storageClassName: gp2
  resources:
    requests:
      storage: 1Gi
